#!/usr/bin/perl

# 
# assert
# Author          : Etienne Grossmann
# Created On      : May     1997
# Last Modified On: January 1998
# Language        : Perl
# Status          : Use with caution!
# 
# (C) Copyright 1998 Etienne Grossmann
# 

use Portuguese::Conjugate ;
use Accent_iso_8859_1;

$rfile = "reference";
die  "file $rfile not found" unless open(VF,"<$rfile");
{ my @vf = <VF>;
  close VF;
  $rs =  join("",@vf); 
  $rs =~ s/\#.*\n*//mg;
  $rs =~ s/\-+//mg;
}
$rs .= "\ndummy:";
foreach $b (@ARGV){
    $b = asc2iso($b);
    $a= conjug( $b );
    if( $rs =~ / \b $b \s* : /x ){
        $rs =~ s/(\b$b\s*:[^:]+)(\b\w+\s*:)/$a$2/ ;
#        print "REPLACING $b in $rfile : \n$1\nWITH\n$a\n";
        print "REPLACING $b in $rfile \n";
    } else {
        print "INSERTING $b in $rfile\n";
        $rs .= "$a";
#        print ">>>$a<<<";
    }
}

$rs =~ s/\ndummy://;
die  "file $rfile not found for saving" unless open(VF,">$rfile");
print VF $rs;
close VF;
